import Head from "next/head";
import { useEffect, useState } from "react";
import { Header } from "../components";
import MeetingCard from "../components/Meeting-card";
import { useDispatch, useSelector } from "react-redux";
import { getMeetingsStore } from "../store/meetings";
import Image from "next/image";
import Router from "next/router";

export default function Home() {
  const state = useSelector((state) => state.meetings);
  const [meetings, setMeetings] = useState([]);
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(getMeetingsStore());
  }, [dispatch]);

  useEffect(() => {
    setMeetings(state.meetings);
  }, [state.meetings]);

  const handleClick = () => {
    Router.push("/create");
  };

  return (
    <>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <div className="min-h-screen flex flex-col">
        <Header />
        <div className="w-full">
          <div className="max-w-6xl mx-auto flex px-8 mt-5 mb-3 sm:px-16">
            <div className="px-2 py-1 bg-purple-700 rounded mr-3 text-white">
              COMING UP
            </div>
            <div className="px-2 py-1 bg-slate-100 rounded mr-3 text-gray-600">
              WRAPPED
            </div>
            <div className="px-2 py-1 bg-slate-100 rounded mr-3 text-gray-600">
              DELETED
            </div>
          </div>
          <div className="max-w-6xl mx-auto px-8 mb-16 sm:px-16">
            <div className="w-full grid sm:grid-cols-2 lg:grid-cols-3 gap-4 flex-wrap">
              {meetings.map((meeting, key) => (
                <MeetingCard key={key} data={meeting} />
              ))}
            </div>
          </div>
          <div className="max-w-6xl mx-auto px-8 sm:px-16 fixed w-full bottom-8 right-1/2 translate-x-1/2 flex justify-end">
            <button
              onClick={handleClick}
              className="flex flex-row gap-2 bg-purple-200 py-3 pl-4 pr-5 rounded-lg items-center border border-black/10 hover:bg-purple-100">
              <Image src="/icons/add-icon.svg" width={30} height={30} />
              <span className="font-bold text-lg">New</span>
            </button>
          </div>
        </div>
      </div>
    </>
  );
}
